when:
  event: tag

steps:
  debian:
    image: node:20
    commands:
      - npm ci && npm run deb

  github:
    image: meltwaterfoundation/github-cli:2.29.0
    commands:
      - gh release create ${CI_COMMIT_TAG} "dist/xtratiler_${CI_COMMIT_TAG##v}-1_amd64.deb" -p -d
    secrets: [github_token]

  docker:
    image: woodpeckerci/plugin-docker-buildx
    # TODO: see https://codeberg.org/woodpecker-plugins/docker-buildx/issues/50
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    settings:
      registry: ghcr.io
      repo: ghcr.io/ldproxy/xtratiler
      auto_tag: true
      force_tag: true
      pull_image: true
      platforms:
        - linux/amd64
        - linux/arm64
      logins:
        - registry: ghcr.io
          username:
            from_secret: ghcr_username
          password:
            from_secret: ghcr_password
