when:
  event: push

steps:
  docker:
    image: woodpeckerci/plugin-docker-buildx
    # TODO: see https://codeberg.org/woodpecker-plugins/docker-buildx/issues/50
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    settings:
      registry: ghcr.io
      repo: ghcr.io/ldproxy/xtratiler
      tags: latest
      force_tag: true
      pull_image: true
      platforms:
        - linux/amd64
#        - linux/arm64
      logins:
        - registry: ghcr.io
          username:
            from_secret: ghcr_username
          password:
            from_secret: ghcr_password

